
stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE ./backend
    - docker push $CONTAINER_IMAGE
  only:
    - main

test:
  stage: test
  image: node:16-alpine
  script:
    - cd backend
    - npm install
    # Add tests here once you have them
    - echo "Tests will go here"
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh $SERVER_USER@$SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $SERVER_USER@$SERVER_IP "cd /home/$SERVER_USER/user-management-system && docker-compose pull && docker-compose up -d"
  environment:
    name: production
    url: https://okdanish.duckdns.org
  only:
    - main
