
version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: userdb
    networks:
      - app-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/userdb
      JWT_SECRET: your_jwt_secret_key_here
      PORT: 5000
    networks:
      - app-network

  # Nginx Service (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Uncomment these lines if you have SSL certificates
      # - ./nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      # - ./nginx/ssl/key.pem:/etc/nginx/ssl/key.pem
    depends_on:
      - backend
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  mongo-data:
    driver: local
